# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/sphinx/conf.py
   builder: html
   fail_on_warning: true

# Optionally build your docs in additional formats such as PDF
#formats:
#   - pdf

build:
  os: ubuntu-20.04
  tools:
    python: "3.7"
  apt_packages:
    - libasound2-dev

# Optionally set the version of Python and requirements required to build your docs
# autodoc imports (!) modules. This means it needs ALL the dependencies, even the optional ones
python:
   version: "3.7"
   install:
   - requirements: requirements.txt
   - requirements: src/jukebox/components/rfid/fake_reader_gui/requirements.txt
   - requirements: docs/sphinx/requirements_pyzmq.txt
   - requirements: docs/sphinx/requirements.txt
