version: "3.9"

services:
  jukebox:
    environment:
      - PULSE_SERVER=tcp:host.docker.internal:4713

  mpd:
    environment:
      - PULSE_SERVER=tcp:host.docker.internal:4713
    volumes:
      - ./docker-development/config/docker.pulse.mpd.conf:/root/.config/mpd/mpd.conf:rw
